import { globSync, readFileSync } from "node:fs"
import { join, relative } from "node:path"
import { describe, expect, it } from "vitest"

/**
 * The ratchet.
 *
 * This is the only thing standing between a design system and the state the
 * server web app is in: 16 components, no select, ad-hoc hex values, and four
 * implementations of the same idea. Every rule below is at zero, and a rule
 * that is at zero cannot quietly become one.
 *
 * The escape hatch is deliberate friction rather than a flag. Append
 * `ratchet-allow: <reason>` on the offending line with at least 20 characters
 * of prose explaining why the system could not express it. Writing that
 * sentence is usually what makes you notice the token you actually wanted.
 */

const ROOT = join(import.meta.dirname, "..")
const SCANNED = [
  "src/components/**/*.tsx",
  "src/routes/**/*.tsx",
  "src/lib/**/*.tsx",
]

/** Files the rules cannot apply to, each with a reason of its own. */
const EXEMPT: Record<string, string> = {
  // The generated route tree is machine-written and contains no styling.
  "src/routeTree.gen.ts": "generated by the TanStack router plugin",
  // Third-party trademarks. Google's four-colour G is specified by their
  // brand guidelines and must not be recoloured or themed; the colour is the
  // mark. These are not theme values and have no light/dark counterpart.
  "src/components/ui/brand-marks.tsx":
    "third-party trademarks whose colours are fixed by brand guidelines and must not be themed",
}

type Rule = {
  name: string
  pattern: RegExp
  why: string
}

const RULES: Array<Rule> = [
  {
    name: "arbitrary-text-size",
    pattern: /text-\[[^\]]*(?:px|rem|em)\]/,
    why: "Use a step from the type scale (text-4xs … text-2xl).",
  },
  {
    name: "arbitrary-radius",
    // `rounded-[inherit]` is allowed: it names no measurement, it defers to
    // whatever the parent already decided.
    pattern: /rounded(?:-[a-z]+)?-\[(?!inherit\])[^\]]+\]/,
    why: "Use rounded-sm / -md / -lg / -xl / -full.",
  },
  {
    name: "arbitrary-shadow",
    pattern: /shadow-\[[^\]]+\]/,
    why: "Use shadow-sm (raised), shadow-md (menus) or shadow-lg (dialogs).",
  },
  {
    name: "arbitrary-z-index",
    pattern: /\bz-\[[^\]]+\]/,
    why: "Use a named layer: z-panel, z-drawer, z-overlay, z-modal, z-popover, z-toast, z-tooltip.",
  },
  {
    name: "bare-z-index",
    // Anything at or above the drawer layer must be named; z-0..z-10 is
    // local stacking inside a component and stays allowed.
    pattern: /\bz-(?:[5-9]\d|\d{3,})\b/,
    why: "A z-index at or above 50 must be a named layer, not a number.",
  },
  {
    name: "colour-literal",
    pattern: /#[0-9a-fA-F]{3,8}\b|\brgba?\(|\bhsla?\(|\boklch\(|\bcolor-mix\(/,
    why: "Colour belongs in src/styles/themes.css. Components name a role.",
  },
  {
    name: "raised-shadow",
    // Elevation is a ring: `ring-1 ring-foreground/10` on a lighter step of
    // the surface ramp. Only a menu (shadow-md) and a dialog (shadow-lg)
    // cast, because they float over content they are not part of.
    pattern: /\bshadow-(?:2?xs|sm|xl|2xl|black|white)(?:\/\d+)?\b/,
    why: "Elevation is a ring, not a shadow. Only shadow-md (menus) and shadow-lg (dialogs) cast.",
  },
  {
    name: "arbitrary-var",
    pattern: /\[var\(--/,
    why: "Map the variable in globals.css @theme and use the utility (border-hairline, text-success).",
  },
  {
    name: "white-black-utility",
    pattern:
      /\b(?:bg|text|border|ring|fill|stroke|divide|outline)-(?:white|black)\b/,
    why: "white and black do not invert. Use foreground/background or an element-* overlay.",
  },
  {
    name: "tailwind-palette",
    pattern:
      /\b(?:bg|text|border|ring|fill|stroke|divide|outline|from|via|to)-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-\d{2,3}\b/,
    why: "Stock Tailwind ramps are not themed. Use a role token.",
  },
  {
    name: "inline-numeric-style",
    pattern: /\b(?:zIndex|fontSize|boxShadow|borderRadius)\s*:\s*['"`]?\d/,
    why: "Inline numeric styles bypass the token layer entirely.",
  },
  {
    name: "dark-variant",
    pattern: /\bdark:[a-z[]/,
    why: "The token layer already inverts. A dark: override is a second source of truth.",
  },
]

const ALLOW = /ratchet-allow:\s*(.{20,})/
const COMMENT = /^\s*(?:\/\/|\/\*|\*)/

/** Vitest runs on Node, so this uses node:fs globSync rather than Bun.Glob. */
function files(): Array<string> {
  return SCANNED.flatMap((pattern) => globSync(pattern, { cwd: ROOT }))
}

function scan(): Array<{
  file: string
  line: number
  text: string
  rule: Rule
}> {
  const violations: Array<{
    file: string
    line: number
    text: string
    rule: Rule
  }> = []
  {
    for (const path of files().map((f) => join(ROOT, f))) {
      const rel = relative(ROOT, path)
      if (rel in EXEMPT) continue
      const lines = readFileSync(path, "utf8").split("\n")
      lines.forEach((text, i) => {
        if (ALLOW.test(text)) return
        // Prose is not styling. A comment explaining why a token is #0a0a0a
        // is the documentation this system wants; banning it would push that
        // explanation out of the file where it belongs.
        if (COMMENT.test(text)) return
        for (const rule of RULES) {
          if (rule.pattern.test(text)) {
            violations.push({ file: rel, line: i + 1, text: text.trim(), rule })
          }
        }
      })
    }
  }
  return violations
}

describe("design system ratchet", () => {
  const violations = scan()

  for (const rule of RULES) {
    it(`has no ${rule.name}`, () => {
      const hits = violations.filter((v) => v.rule.name === rule.name)
      const report = hits
        .map((v) => `  ${v.file}:${v.line}\n    ${v.text.slice(0, 120)}`)
        .join("\n")
      expect(
        hits.length,
        hits.length === 0
          ? ""
          : `${rule.why}\n${report}\n\nIf the system genuinely cannot express this, append ` +
              `\`ratchet-allow: <at least 20 characters of reason>\` to the line.`
      ).toBe(0)
    })
  }

  it("scans a meaningful number of files", () => {
    // Guards against a glob typo silently turning the whole suite green.
    expect(files().length).toBeGreaterThan(40)
  })
})
